#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# Calculate global envelopes
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
#
#
# Author: Michael Kalyuzhny
# Created: 04/04/23
# Modified: 05/04/23 
#
# Gets two input files, uses them to construct global envelopes and outputs the envelope.
# Runs very quietly.
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

#install.packages("GET")

options(warn = -1) # Avoid printing warnings
require('GET', quietly = TRUE)

# Load input generated by Matlab

R_res = as.matrix(read.csv('r_res.csv',header = FALSE))
R_obs = as.matrix(read.csv('r.csv',header = FALSE))

# Create global envelope from input

cs = create_curve_set(list(r = 1:20, obs = c(R_obs), sim_m = t(R_res)))
e <- global_envelope_test(cs, type = "erl")

# Export

d = data.frame(hi = e$hi, lo = e$lo)
write.csv(d, file = 'export_rel.csv')
